.github: add release template for RCs from master branch
cilium/release pull request #11
Opened 2021-11-19 13:57 UTC by aanm

Signed-off-by: André Martins <andre@cilium.io>

2021-11-19 23:01 UTC, joestringer requested changes

2021-11-19 23:01 UTC, joestringer commented on .github/ISSUE_TEMPLATE/release_template_rc_master.md
> +Thank you for the bugs reported found in the previous RC. There are [vX.Y.Z-rcW OSS docs](https://docs.cilium.io/en/vX.Y.Z-rcW) available if you want to pull this version & try it out.
nit, RCs are partly about bugs, but also about docs improvements, other feature freeze exception PRs, etc. Broadly, contributions.

```suggestion
Thank you for testing and contributing to the previous RC. There are [vX.Y.Z-rcW OSS docs](https://docs.cilium.io/en/vX.Y.Z-rcW) available if you want to pull this version & try it out.
```

2021-11-19 23:01 UTC, joestringer commented on .github/ISSUE_TEMPLATE/release_template_rc_master.md
> +## Post-release
Are there any post-release steps?

2021-11-19 23:04 UTC, aanm commented on .github/ISSUE_TEMPLATE/release_template_rc_master.md
> +## Post-release
No, somehow I forgot to remove this.

2021-11-19 23:28 UTC, aanm commented on .github/ISSUE_TEMPLATE/release_template_rc_master.md
> +     [Re-trigger a build in quay.io](https://docs.cilium.io/en/v1.9/contributing/development/images/#update-cilium-builder-and-cilium-runtime-images)
Yes, this can be removed because this is RC from master branch.

2021-11-23 19:18 UTC, joestringer approved these changes

2021-11-23 21:58 UTC, merged