changelog: Add --exclude-pr-references option
cilium/release pull request #218
Opened 2024-06-20 21:08 UTC by chancez

--exclude-pr-references configures the `release` tool to not include references to pull requests in the generated changelog.

We have some internal projects that we would like to re-use the cilium/release tooling for, but since the projects are private, the references to the PR, repository and author is a bit unnecessary, and potentially confusing to end-users, so this PR adds an option to not include that information in the generated changelog.

2024-06-20 21:12 UTC, michi-covalent approved these changes
lgtm let's give @aanm some time to review this as well ⏲️

2024-06-21 15:26 UTC, aanm requested changes
Thanks for the ping, please block until https://github.com/cilium/release/pull/196 is merged.

2024-06-21 15:47 UTC, chancez commented
@aanm How long until #196 is ready? Looks like it might take a while? These changes should hopefully be minor enough that conflicts are easy to resolve, no?

2024-07-09 18:50 UTC, aanm commented
@chancez sorry for taking a lot of time. #196 is now ready.

2024-07-12 00:30 UTC, chancez commented
@aanm rebased and ready for review

2024-07-12 13:58 UTC, aanm approved these changes

2024-07-12 13:58 UTC, merged