.github: Mention upgrade/roadmap updates
cilium/release pull request #47
Opened 2022-07-25 21:56 UTC by joestringer

Add a point to review the status of features in the upgrade guide,
roadmap so that the docs are consistent upon release.

2022-07-25 21:57 UTC, qmonnet approved these changes

2022-07-25 22:02 UTC, michi-covalent approved these changes

2022-07-27 19:20 UTC, aanm requested changes

2022-07-27 19:20 UTC, aanm commented on .github/ISSUE_TEMPLATE/release_template_minor.md
> +- [ ] Update the upgrade guide and roadmap for any features that changed status.
which roadmap?

2022-07-27 21:18 UTC, joestringer commented on .github/ISSUE_TEMPLATE/release_template_minor.md
> +- [ ] Update the upgrade guide and roadmap for any features that changed status.
I pushed an update with the link.

2022-07-28 09:57 UTC, aanm approved these changes
TIL about that roadmap

2022-07-28 15:35 UTC, merged