Avoid moving pending backports to new project
cilium/release pull request #70
Opened 2022-11-18 00:52 UTC by joestringer

As part of backport tracking, we set labels on PRs and attempt to ensure
that when a backport is "done" for a branch, the labels are set and this
controls which column in the versioned project that the PR ends up in.

When we do a new release, the previous behaviour of this tool was to
move all "pending" backports to the project for the next release
version. However, sometimes an earlier step is missed, which means that
PRs that have already been backported eg to 1.12.4 are marked as
"pending" in 1.12.4. This tool then mistakenly moves them to
"pending to 1.12.5", which is incorrect and confusing.

In the absence of a better system to control these, at least avoid
propagating the mistake in this tool. By default, prevent the release
manager from moving "pending backports" to a new project. There is an
override to allow moving the pending backports if they are *really*
pending, but hopefully this at least stops the release long enough to
make sure the backports are in the right status in the backport.

2022-11-18 00:53 UTC, joestringer commented
The real solution is to figure out how to avoid skipping the step to set the "backport-done" labels when the backport occurs, but I don't know a good way to do that right now. The best we can do in this tool is at least ensure those steps are followed during the release process.

2022-11-18 00:54 UTC, joestringer commented on cmd/projects/projects.go
> +					return fmt.Errorf("Found unexpected pending PR in project. Please ensure that all backported PRs have been moved to the done column.")
I'd like to have a URL in this to point to, but I couldn't figure out how to get the canonical github page to look into this since the inputs to the function seem to be more about columnIDs rather than project numbers.

2022-11-18 08:37 UTC, aanm requested changes
I think this will also solve it?
```diff
diff --git a/cmd/projects/projects.go b/cmd/projects/projects.go
index 780ec67..54abba6 100644
--- a/cmd/projects/projects.go
+++ b/cmd/projects/projects.go
@@ -181,6 +181,32 @@ func (pm *ProjectManagement) syncCards(ctx context.Context, currVer, nextVer str
                if prID == 0 {
                        continue
                }
+               if pr.GetMerged() {
+                       backportDoneLbl := labelName(doneBackportLbl, currVer)
+                       fmt.Fprintf(os.Stdout, "setting label %q for PR %d since it was already merged\n", backportDoneLbl, prNumber)
+                       _, _, err := pm.ghClient.Issues.AddLabelsToIssue(ctx, pm.owner, pm.repo, pr.GetNumber(), []string{backportDoneLbl})
+                       if err != nil {
+                               return err
+                       }
+                       needsBackportLbl := labelName(needsBackportLbl, currVer)
+                       fmt.Fprintf(os.Stdout, "removing label %q for PR %d since it was already merged\n", needsBackportLbl, prNumber)
+                       _, err = pm.ghClient.Issues.RemoveLabelForIssue(ctx, pm.owner, pm.repo, pr.GetNumber(), needsBackportLbl)
+                       if err != nil {
+                               return err
+                       }
+                       pendingBackportLbl := labelName(pendingBackportLbl, currVer)
+                       fmt.Fprintf(os.Stdout, "removing label %q for PR %d since it was already merged\n", pendingBackportLbl, prNumber)
+                       _, err = pm.ghClient.Issues.RemoveLabelForIssue(ctx, pm.owner, pm.repo, pr.GetNumber(), pendingBackportLbl)
+                       if err != nil {
+                               return err
+                       }
+
+                       // Get the PR again with the latest labels
+                       pr, _, err = pm.ghClient.PullRequests.Get(ctx, pm.owner, pm.repo, prNumber)
+                       if err != nil {
+                               return err
+                       }
+               }
                // If it is not backported them move it to the right column in the
                // next project.
                moveToColumnID := nextColumnID

```

2022-11-18 16:33 UTC, joestringer commented
@aanm is `pr` in that context the original PR or the backport PR? Seems like the original PR, meaning that the logic is checking if the PR is merged to master then it assumes the PR is backported to older branches.

2022-11-18 16:50 UTC, aanm commented
@joestringer 

> @aanm is `pr` in that context the original PR or the backport PR? Seems like the original PR, meaning that the logic is checking if the PR is merged to master then it assumes the PR is backported to older branches.

It is the original PR. 

> meaning that the logic is checking if the PR is merged to master

correct

> then it assumes the PR is backported to older branches.

Now, I'm lost, so?

2022-11-18 21:07 UTC, joestringer commented
> > then it assumes the PR is backported to older branches.
> 
> Now, I'm lost, so?

This would check if the PR is merged to master and if it is + the `backport-pending/X.Y` label is set, we then _assume_ that the backport is already merged. But it's not checking that vX.Y branch actually contains the backport. The backport could still be pending.

2022-11-19 00:46 UTC, aanm commented on cmd/projects/projects.go
> +					return fmt.Errorf("Found unexpected pending PR in project. Please ensure that all backported PRs have been moved to the done column.")
@joestringer Why not give the URL of the PR that is pending? It's a reference that's better than nothing.

2022-11-22 15:46 UTC, aanm approved these changes

2022-11-22 18:21 UTC, merged